export enum Navigation {
  ROOT = '/',
  LOGIN = '/login',
  REGISTER_CUSTOMER = '/customers/register',
  REGISTER_ORGANISER = '/organisers/register',
  RESET_PASSWORD = '/reset-password',
  CUSTOMERS = '/customers',
  CUSTOMERS_PROFILE = '/customers/profile',
  CUSTOMERS_CART = '/customers/cart',
  CUSTOMERS_MY_TICKETS = '/customers/my-tickets',
  CUSTOMERS_CHECKOUT_FOR_ORGANISER = '/customers/checkout/:sellerId',
  ORGANISERS = '/organisers',
  ORGANISERS_PROFILE = '/organisers/profile',
  ORGANISERS_ADD_EVENT = '/organisers/add-event',
}
