# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - ewb-frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          cd ./frontend
          npm install
          npm run build --if-present
          npm run test --if-present
        env:
            VITE_API_URL: ${{ secrets.VITE_API_URL }}
            VITE_FRONTEND_PORT: ${{ secrets.VITE_FRONTEND_PORT }}
            VITE_HOST: ${{ secrets.VITE_HOST }}
            VITE_DEFAULT_HTTP_TIMEOUT: ${{ secrets.VITE_DEFAULT_HTTP_TIMEOUT }}

      - name: Zip artifact for deployment
        run: |
          cd frontend/dist
          zip ../../release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4C00CDC7D3DE41A6BF1A455E7A5D41CA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_364BC71190EB4CBA9C5BCEF3FC4FB579 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4DE754749F7148718DD168AEAFF0A52E }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ewb-frontend'
          slot-name: 'Production'
          package: release.zip
          
