# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - ewb-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: Install dotnet-ef
        run: dotnet tool install --global dotnet-ef --version 9.*
  
      - name: Debug Connection String
        run: echo "Conn: $env:ConnectionStrings__DefaultConnection"
        shell: pwsh
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.RESELLIO_DB_CONN_STRING }}
  
      - name: Update Database
        run: dotnet ef database update --project ./backend/ResellioBackend/ResellioBackend.csproj --startup-project ./backend/ResellioBackend
        shell: pwsh
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.RESELLIO_DB_CONN_STRING }}

      - name: Build with dotnet
        run: dotnet build ./backend/ResellioBackend/ResellioBackend.sln --configuration Release

      - name: dotnet publish
        run: dotnet publish ./backend/ResellioBackend/ResellioBackend.sln -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_86769916734D4B2FBB6FF65AD3A0217C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A6930D69D45649159C82080612E92779 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_60A81CC1AF6947388C9C83891E22BE08 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ewb-backend'
          slot-name: 'Production'
          package: .
          
